version: "3.9"

## say e.g. `docker-compose --env-file .env.dev up -d`

services:

  gpu-jupyter:
    image: gpu-jupyter
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - type: bind
        source: ${HOME}/Projects/aix
        target: /home/jovyan/work
      - type: bind
        source: ${DATAPOOL}/nn
        target: /data
    ports:
      - "8848:8888" # JupyterLab
    user: root
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu, utility]

  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=neo4j/nonstandard # Only has effect if db does not already exist
    volumes:
      - type: bind
        source: ${DATAPOOL}/soul/neo4j/data
        target: /data
      - type: bind
        source: ${DATAPOOL}/soul/neo4j/logs
        target: /logs
      - type: bind
        source: ${DATAPOOL}/soul/neo4j/import
        target: /var/lib/neo4j/import
      - type: bind
        source: ${DATAPOOL}/soul/neo4j/plugins
        target: /plugins
    ports:
      - "7373:7373"
      - "7474:7474"
      - "7687:7687"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
    ports:
      - "5672:5672"
      - "15672:15672" # management

  flower:
    image: mher/flower
    environment:
      - FLOWER_BROKER
      - FLOWER_BROKER_API
    ports:
      - "5555:5555" # flower
